server:
  port: 8081
logging:
  level:
    root: INFO
spring:
  security:
    oauth2:
      client:
        registration:
          local:
            client-id: "client_id"
            client-secret: "secret"
            client-authentication-method: "client_secret_basic"
            scope: 
              - "openid"
              - "profile"
              - "offline_access"
        provider:
          local:
            issuerUri: http://localhost:9000
            # user-name-attribute: cognito:username
springdoc:
  swagger-ui:
    tryItOutEnabled: true
    oauth:
      # additionalQueryStringParams: 
      #   audience: "audience"
      clientId: client_id
      clientSecret: secret
      scopes: openid,profile,offline_access
      useBasicAuthenticationWithAccessCodeGrant: true
